[application]

name = "countryinfo"

default_platform = "web"

out_dir = "dist"

asset_dir = "assets"

[web.app]
title = "CountryInfo"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
